from .carbs import CarbRing
from .utils import FloatArray, Frame

def ring_get_centroid_py(ring: CarbRing): ...
def ring_get_centroid_and_normal_py(ring: CarbRing): ...
def ring_get_frame_py(ring: CarbRing) -> Frame: ...
def ring_calc_pucker_amplitude_py(ring: CarbRing) -> float: ...
def paperchain_colormap(ring: CarbRing) -> FloatArray:
    """
    Calculate the color for a ring, using the PaperChain algorithm.

    Returns:
        The calculated color as an RGB [0, 1] float array.
    """
    ...
