from utils import DoubleArray

class Frame:
    def __init__(
        self,
        origin: DoubleArray,
        up: DoubleArray,
        forward: DoubleArray,
        right: DoubleArray,
    ): ...
    @property
    def origin(self) -> DoubleArray: ...
    @origin.setter
    def origin(self, v: DoubleArray): ...
    @property
    def up(self) -> DoubleArray: ...
    @up.setter
    def up(self, v: DoubleArray): ...
    @property
    def forward(self) -> DoubleArray: ...
    @forward.setter
    def forward(self, v: DoubleArray): ...
    @property
    def right(self) -> DoubleArray: ...
    @right.setter
    def right(self, v: DoubleArray): ...
    def copy(self) -> Frame: ...
    def align(self, forward: DoubleArray):
        """Rotate the frame to align with a forward vector."""
        ...
